version: "3"
services:
  client:
    image: node:8.11-alpine
    working_dir: /application
    user: node
    volumes:
      - ./application/client:/application:cached
    ports:
      - 4200:4200
    command: "yarn start --host 0.0.0.0"
